Why Use Pandas?

Pandas allows us to analyze big data and make conclusions based on statistical theories.
Pandas can clean messy data sets, and make them readable and relevant.
Relevant data is very important in data science.

What Can Pandas Do?

Pandas gives you answers about the data. Like:

Is there a correlation between two or more columns?
What is average value?
Max value?
Min value?

Pandas are also able to delete rows that are not relevant, or contains wrong values, like empty or NULL values. This is called cleaning the data.

1 Python Series

In [71]:
import pandas as pd

# dummpy data
a = [1,2,3]

print('Show the data using series:\n\n', pd.Series(a))

Show the data using series:

 0    1
1    2
2    3
dtype: int64


Lable: Use to get the first value of the searies

In [72]:
print('\n\nGet single lable:\n\n', pd.Series(a)[0])



Get single lable:

 1


Manually Lable name provide using `index` argument in `Series` method: As per this set manully index in series data

In [73]:
print('\n\nSet manual name in Series:\n\n', pd.Series(a, index=['a','b','c']))



Set manual name in Series:

 a    1
b    2
c    3
dtype: int64


In `Series` method also pass a `dictnory` data in key value pare.
Also if wants a limited data to show via Series then in index argument only pass those key which you want to show.

DataFrame: Its like a hote table where Series only like a columns data. For using `pandas` `DataFrame` use it as an method in it and this method have many more argrumnets which have specific work roles to perform.

In pandas dataframe have very important sub methods which plays a very important roles and I am discussing only them:

In [74]:
# Load a csv file to read its data
df = pd.read_csv('doc/data.csv')
pd.options.display.max_rows = 200
print('Check data:\n', df.to_string()) # to_string() use to show the compete data

Check data:
      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23 

Want to show a specific number of rows of dataframw like by defult when print the df data it will only show the first and last 5 rows but when use `in_string()` method it will show the max rows but it also have limitation.

In this case use `pd.options.display.max_rows`

Here you see that on output section have note of `output` where provide a link in which click to show the compete data in text editor.

In [75]:
print('Max rows using pd.options.display.max_rows:\n', df)

Max rows using pd.options.display.max_rows:
      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         6

Use `head` method to fetch the specific number of rows form the data bydefualt head method show first 5 rows data with column.

In [76]:
print('Head method using to show the data:\n\n', df.head())

Head method using to show the data:

    Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [77]:
print('Head method using to show the data:\n\n', df.head(10))

Head method using to show the data:

    Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


Data show form bottom use `tail` method same as head but it fetch the data form bottom by default 5 or define mannually.

In [78]:
print('Bottom data using trail method\n\n', df.tail())

Bottom data using trail method

      Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


In [79]:
print('Bottom data using trail method\n\n', df.tail(10))

Bottom data using trail method

      Duration  Pulse  Maxpulse  Calories
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


Want to know the basic information about the data like:

1. Index data range
1. data columns
1. Non-null values count
1. Column wise there data-type
1. Count of total same type data-types
1. size of the complete data

Use `info` method to get these details.

>>>Note: Empty values, or Null values, can be bad when analyzing data, and you should consider removing rows with empty values. This is a step towards what is called cleaning data, and you will learn more about that in the next chapters.

In [80]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None


## Data Cleaning

Data cleaning means fixing bad data in your data set.

Bad data could be:

1. Empty cells
1. Data in wrong format
1. Wrong data
1. Duplicates

Our data have following bad data also:

1. The data set contains some empty cells ("Calories" in row 18 and 28).
1. The data set contains wrong data ("Duration" in row 7).
1. The data set contains duplicates (row 11 and 12).

### Empty cells

1. Empty cells can potentially give you a wrong result when you analyze data.
1. One way to deal with empty cells is to remove rows that contain empty cells.
1. This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.

First of check how many null values have in the dataset. for that use the `isnull` which provides a boolean values 

In [81]:
# isnull() only provide a complete True False but what if we want a number of how many null values have then
print('Check null values in our dataset:\n\n', df.isnull())

Check null values in our dataset:

      Duration  Pulse  Maxpulse  Calories
0       False  False     False     False
1       False  False     False     False
2       False  False     False     False
3       False  False     False     False
4       False  False     False     False
5       False  False     False     False
6       False  False     False     False
7       False  False     False     False
8       False  False     False     False
9       False  False     False     False
10      False  False     False     False
11      False  False     False     False
12      False  False     False     False
13      False  False     False     False
14      False  False     False     False
15      False  False     False     False
16      False  False     False     False
17      False  False     False      True
18      False  False     False     False
19      False  False     False     False
20      False  False     False     False
21      False  False     False     False
22      False  False 

In [82]:
# isnull() with sum() mehtod will provide what we want.
print('Check null values in our dataset in numbers:\n\n', df.isnull().sum())

Check null values in our dataset in numbers:

 Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64


As per same we also have a mehtod which provide the total number of not null values.
Use notnull() method with sum() method or direct only use notnull() method but it only gives a True False. 

In [83]:
print('Check null values in our dataset:\n\n', df.notnull().sum())

Check null values in our dataset:

 Duration    169
Pulse       169
Maxpulse    169
Calories    164
dtype: int64


Know time to remove the null values from the data.
For this use a `dropna()` method which remove all rows where found any null values.
Also this mehtod a multiple arguments by which we control in wich condition we wants to remove the rows. Like:

1. if any null value found in the row will remove
1. if all null in row then remove
1. if any combination of columns only have all or any null value then remove the row. 
1. Like same have other many cases but we only focues in these.

In [84]:
not_null_data = df.dropna()
print('No null values data:\n\n', not_null_data)

No null values data:

      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132    

Check null values count to verify is removed null holding rows or not using `isnull` with `sum` method.

In [85]:
print('Check new dataset null values count:\n\n', not_null_data.isnull().sum())

Check new dataset null values count:

 Duration    0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64


In [86]:
# As per this only have 164 rows means the 5 rows who had null values are removed from this data set.
print('Check count of total available data:\n\n', not_null_data.notnull().sum())

Check count of total available data:

 Duration    164
Pulse       164
Maxpulse    164
Calories    164
dtype: int64


>>>Note: By default, the dropna() method returns a new DataFrame, and will not change the original. If you want to change the original DataFrame, use the inplace = True argument in `dropna()` method

Also we can replace the null vaues using `fillna` method which provide a facility to replace the null values as per what we want to add on those null values.
But this method have limitation like this provide the following facilities:

1. as the privous rows data on following columns bases null value
1. same as next rows data on following columns base null value
1. replace as per our choice data

See these rows where replace the valeus:

1. The data set contains some empty cells ("Calories" in row 18 and 28).

>>>Note: in `fillna` mehtod also pass `inplace=True` argument and value to replace current dataframe value.

In [88]:
fill_null_values_data = df.fillna(1000)
print('Fill null value using fillna method:\n\n', fill_null_values_data)

Fill null value using fillna method:

      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112    1000.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    1

Also we can Replace Only For Specified Columns like `Calories` columns row `18` have null values whcih we replace which 1000.
Know replace only this columns null values not hole datasets.

In [93]:
fill_null_values_data_in_single_column = df # In this line only load the datafame in other variable
fill_null_values_data_in_single_column['Calories'].fillna(2000)
print('Chane single column Calories null values:\n\n', fill_null_values_data_in_single_column)

Chane single column Calories null values:

      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112    2000.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60

Replace Using Mean, Median, or Mode

A common way to replace empty cells, is to calculate the mean, median or mode value of the column.

Pandas uses the `mean()` `median()` and `mode()` methods to calculate the respective values for a specified column:

This is also a good idea to replace null values as per logics because manully values might make big difference in data but using mehtod will look like similer as other datas.

In [94]:
# At first get the complere columns mean then apply that on null values
measn_of_calories_column = pd.read_csv('doc/data.csv')
mean_value = measn_of_calories_column['Calories'].mean()
print('Mean values of calories columns is:\n\n', mean_value)
print('Replace null of calories column with mean valeus:\n\n', measn_of_calories_column.fillna(mean_value))
# Looke 17th row

Mean values of calories columns is:

 375.79024390243904
Replace null of calories column with mean valeus:

      Duration  Pulse  Maxpulse     Calories
0          60    110       130   409.100000
1          60    117       145   479.000000
2          60    103       135   340.000000
3          45    109       175   282.400000
4          45    117       148   406.000000
5          60    102       127   300.000000
6          60    110       136   374.000000
7          45    104       134   253.300000
8          30    109       133   195.100000
9          60     98       124   269.000000
10         60    103       147   329.300000
11         60    100       120   250.700000
12         60    106       128   345.300000
13         60    104       132   379.300000
14         60     98       123   275.000000
15         60     98       120   215.200000
16         60    100       120   300.000000
17         45     90       112   375.790244
18         60    103       123   323.000000
19         

Similer like `mean` method have `medion` and `mode` method. Same find the value and replace which these values.

### Data in wrong format

Cells with data of wrong format can make it difficult, or even impossible, to analyze data.
To fix it, you have two options: remove the rows, or convert all cells in the columns into the same format.

Convert Into a Correct Format: For converting into right formate for that need to know the columns `datatype` and as per that decide to make it similier like other. If you are fiale to conver into right formate then remove the data is best option.

Removing Rows: In this case if we wants to remove the rows where have null values. For that use the `dropna` method for single column like this:

Remeber in calories have null value on row 17:

In [96]:
single_row_null_value_remove = pd.read_csv('doc/data.csv')
print('Rmeove null vaues form calories columns:\n\n', single_row_null_value_remove.dropna(subset=['Calories'])) 

Rmeove null vaues form calories columns:

      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45 

>>>Check row 17 is removed.

### Wrong Data

"Wrong data" does not have to be "empty cells" or "wrong format", it can just be wrong, like if someone registered "199" instead of "1.99".

Sometimes you can spot wrong data by looking at the data set, because you have an expectation of what it should be.

If you take a look at our data set, you can see that in row 7, the duration is 450, but for all the other rows the duration is between 30 and 60.

It doesn't have to be wrong, but taking in consideration that this is the data set of someone's workout sessions, we conclude with the fact that this person did not work out in 450 minutes.

In [102]:
wrong_dataset = pd.read_csv('doc/data.csv')
wrong_dataset.at[7, 'Duration'] = 450 # Created wrong data in dataset row 7
print(wrong_dataset.head(10))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7       450    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


How can we fix wrong values, like the one for "Duration" in row 7?

One way to fix wrong values is to replace them with something else.
In our example, it is most likely a typo, and the value should be "45" instead of "450", and we could just insert "45" in row 7:

For small data sets you might be able to replace the wrong data one by one, but not for big data sets.
To replace wrong data for larger data sets you can create some rules, e.g. set some boundaries for legal values, and replace any values that are outside of the boundaries.

One way is to:
Loop through all values in the "Duration" column.
If the value is higher than 120, set it to 120:

In [103]:
for x in wrong_dataset.index:
  if wrong_dataset.loc[x, "Duration"] > 120:
    wrong_dataset.loc[x, "Duration"] = 120
    
print('Replace greater then 120 values:\n\n', wrong_dataset)  

Replace greater then 120 values:

      Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7         120    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130  

Another way of handling wrong data is to remove the rows that contains wrong data.

This way you do not have to find out what to replace them with, and there is a good chance you do not need them to do your analyses.

In [106]:
wrong_dataset.at[7, 'Duration'] = 450 # Created wrong data in dataset row 7
for x in wrong_dataset.index:
  if wrong_dataset.loc[x, "Duration"] > 120:
    wrong_dataset.drop(x, inplace=True)
    
print('Remove greater then 120 values:\n\n', wrong_dataset.head(10)) 

Remove greater then 120 values:

     Duration  Pulse  Maxpulse  Calories
0       60.0  110.0     130.0     409.1
1       60.0  117.0     145.0     479.0
2       60.0  103.0     135.0     340.0
3       45.0  109.0     175.0     282.4
4       45.0  117.0     148.0     406.0
5       60.0  102.0     127.0     300.0
6       60.0  110.0     136.0     374.0
8       30.0  109.0     133.0     195.1
9       60.0   98.0     124.0     269.0
10      60.0  103.0     147.0     329.3


### Removing Duplicates

Duplicate rows are rows that have been registered more than one time.

By taking a look at our test data set, we can assume that row 11 and 12 are duplicates.

To discover duplicates, we can use the duplicated() method.

The duplicated() method returns a Boolean values for each row:

In [109]:
duplicate_dataset = pd.read_csv('doc/data.csv')
duplicate_dataset.loc[12] = [60,100,120,250.7] # Make row 12 dublicate
print('Duplicate data:\n\n', duplicate_dataset.head(15))

Duplicate data:

     Duration  Pulse  Maxpulse  Calories
0         60    110       130     409.1
1         60    117       145     479.0
2         60    103       135     340.0
3         45    109       175     282.4
4         45    117       148     406.0
5         60    102       127     300.0
6         60    110       136     374.0
7         45    104       134     253.3
8         30    109       133     195.1
9         60     98       124     269.0
10        60    103       147     329.3
11        60    100       120     250.7
12        60    100       120     250.7
13        60    104       132     379.3
14        60     98       123     275.0


Find duplicate using the `duplicate` method

In [110]:
print('Get number of dublicate values:\n\n', duplicate_dataset.duplicated().sum())

Get number of dublicate values:

 8


For removing the duplicate use `drop_duplicates` method

In [115]:
print('Remove the duplicate valeus using drop_duplicates method:\n\n', duplicate_dataset.drop_duplicates(inplace=True))

Remove the duplicate valeus using drop_duplicates method:

 None


In [116]:
print('Check dubplicate values know:\n\n', duplicate_dataset.duplicated().sum())

Check dubplicate values know:

 0


## Data Correlations and Plotting remains